# Global VM Settings 
[global/vm]
; Used for top aligned bars
margin-bottom = 0 

; Used for bottom aligned bars
margin-top = 0

; Include an external
include-file = ~/.config/polybar/colors.ini

;; Bar Settings 

[bar/example]
; If unspecifies, the application will pick the first one it finds.
; $ polybar -m | cut -d ':' -f 1 
; $ xrandr -q | grep " connected" | cut -d ' ' -f1
monitor = 

; Require the monitor to be in connected state
; XRandR sometimes reports my monitor as being disconnected (when in use)
monitor-strict = false

; Prefer fixed center position for the `modules-center` block
; When false, the center position will be based no the size of the other blocks.
fixed-center = true
width = 100%
height = 30pt
radius = 10

background = #2e3742
foreground = ${color.white}

# line-size = 3pt

border-size = 3pt
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${color.orange}

#font-0 = monospace:size=14;2
font-0 = "Hack Nerd Font Mono:size=14;4"

modules-left = xworkspaces
modules-right = ethernet_status hack_the_box_vpn target date battery

cursor-click = pointer

; wm-restack = generic
wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/ethernet_status]
type = custom/script
interval = 2
exec = ~/.config/polybar/scripts/ethernet_status.sh

[module/hack_the_box_vpn]
type = custom/script
interval = 2
exec = ~/.config/polybar/scripts/hack_the_box_vpn.sh

[module/target]
type = custom/script 
interval = 2 
exec = ~/.config/polybar/scripts/target.sh

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = 
label-active-foreground = ${color.yellow}
label-active-padding = 1

label-occupied = %name%
label-occupied-foreground = ${color.red}
#label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${color.red}
#label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${color.white}
label-empty-padding = 1

[module/baterry]
type = internal/battery

full-at = 99
battery = BAT1
adapter = ACAD

poll-interval = 2
time-format = %H:%M 

format-charging = <animation-charging>
format-discharging = <ramp-capacity>

format-full = <label-full>
format-full-foreground = ${color.white}
label-full = <U+F583>

ramp-capacity-0 = <U+F579>
ramp-capacity-1 = <U+F57A>
ramp-capacity-2 = <U+F57B>
ramp-capacity-3 = <U+F57C>
ramp-capacity-4 = <U+F57D>
ramp-capacity-5 = <U+F57E>
ramp-capacity-6 = <U+F57F>
ramp-capacity-7 = <U+F580>
ramp-capacity-8 = <U+F581>
ramp-capacity-9 = <U+F578>
ramp-capacity-foreground = ${color.white}

animation-charging-0 = <U+F579>
animation-charging-1 = <U+F57A>
animation-charging-2 = <U+F57B>
animation-charging-3 = <U+F57C>
animation-charging-4 = <U+F57D>
animation-charging-5 = <U+F57E>
animation-charging-6 = <U+F57F>
animation-charging-7 = <U+F580>
animation-charging-8 = <U+F581>
animation-charging-9 = <U+F578>
animation-charging-foreground = ${color.white}
animation-charging-framerate = 750

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/date]
type = internal/date
interval = 1

date = %d-%m %H:%M:%S

label = %date%
label-foreground = ${color.white}

[settings]
screenchange-reload = true
pseudo-transparency = true
